# https://docs.docker.com/build/ci/github-actions/examples/
name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version-file: ".python-version"

      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1

      - name: Verify installations
        run: |
          python --version
          uv --version

      - name: Install tools
        run: |
          uv tool install ruff
          uv tool install black

      - name: Install project dependencies
        run: uv sync --locked

      - name: Lint Format
        run: uv tool run black --check .

      - name: Lint Check
        run: uv tool run ruff check

      - name: Run tests
        run: uv run pytest
